// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcgkfkmrbfpmhxyzrcxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jZ2tma21yYmZwbWh4eXpyY3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODc5ODcsImV4cCI6MjA3MDQ2Mzk4N30.ItPAeo3v0PUmlXM6T86D4WvEq8wsUK4VrUJooHhes5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});